### ISSUE TITLE
[PE-D][Tester D] Duplicate items allowed when editing items

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-3/tp#201] opened 2024-11-08 14:08 UTC
![Screenshot 2024-11-08 154025.png](https://raw.githubusercontent.com/ZiliaAJY/ped/main/files/dc3a066f-c5a2-40b6-8d7b-78642b2fde89.png)

By default, the program does not allow duplicate items to be added. However, when i edit another item's name (e.g. Tissue Paper) in the list to be the same name as an existing item (e.g. Origami paper), the list then contains duplicate items.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ZiliaAJY/ped#7

**Comment by jemehgoh** [comment] 2024-11-08 14:11
Duplicate of #186.

**Closed by jemehgoh** 2024-11-08 14:11 UTC
